### ISSUE TITLE
Some review comments. Salt to taste. 

### ISSUE THREAD

**Issue by yudistrange** [navyad/moviematch#10]
1. https://github.com/navyad/moviematch/blob/40b275572ee0d43eb22d7b106d688b532c792abc/lib/moviematch.ex#L12
Prefer using `case` over `cond` for static matches. For instance 
```
case movie_count do 
    1 -> true
    0 -> false
end
```
And if there are only two branches why not if?

2. https://github.com/navyad/moviematch/blob/40b275572ee0d43eb22d7b106d688b532c792abc/lib/moviematch.ex#L21
This is not uselful in the `with block because you are pattern matching everything. You can move this into the map in next line `is_found: is_movie?(json_response)`

3. https://github.com/navyad/moviematch/blob/40b275572ee0d43eb22d7b106d688b532c792abc/lib/imdb.ex#L6
Why declare a module constant if its only being used once?

4. https://github.com/navyad/moviematch/blob/40b275572ee0d43eb22d7b106d688b532c792abc/lib/imdb.ex#L44
with blocks use `<-` iirc

5. https://github.com/navyad/moviematch/blob/40b275572ee0d43eb22d7b106d688b532c792abc/lib/imdb.ex#L12
This fn can do with some refactoring. One way to go about it could be to create a struct which has the requisite fields. That way you can sort of have some guarantees on the parsed API response. 

6. https://github.com/navyad/moviematch/blob/40b275572ee0d43eb22d7b106d688b532c792abc/lib/imdb.ex#L29
Same as above

7. https://github.com/navyad/moviematch/blob/40b275572ee0d43eb22d7b106d688b532c792abc/lib/api_client.ex#L16
As a general safety guideline prefer using the safe version of fns rather than the unsafe ones (fns which end with !). With safe fns you can pattern match on `{:ok, response}` or {:error, error}` but with the unsafe fns you would have to catch the exceptions if you don't want the process to die.

**Comment by navyad** [comment]
[commit](https://github.com/navyad/moviematch/commit/9b37a6260b5719d40920c0b551f0c293db7770c8) has tackled: 1, 2 , 4 and 7.
